#!/bin/bash

function show_help() {
  echo "Usage: zip_pdx <dir> [-s]"
  echo "Zips every pdx in a directory"
  echo "Options:"
  echo "  -s    Single fire at target dir"
  echo "  -h    Display this help message"
}

function singlefire() {
  local item="$1"
  if [ -d "$item" ] && [ -f "$item/pdxinfo" ]; then #
    zipname="${item}.zip"
    if [ ! -f "$zipname" ]; then
      zip -r "$zipname" "$item" >&2 #
    else
      echo "$zipname already exists" >&2
      exit 1
    fi
  else
    echo "$item: pdxinfo not found" >&2
    exit 1
  fi
}

function zip_dir() {
  local dir_to_loop="$1"
  for item in "$dir_to_loop"/*; do
    if [ -d "$item" ] && [ -f "$item/pdxinfo" ]; then
      zipname="${item}.zip"
      if [ ! -f "$zipname" ]; then
        zip -r "$zipname" "$item"
      fi
    fi
  done
}

if [ "$#" -lt 1 ]; then
  show_help
  exit 1
fi

case "$2" in
  -s)
    singlefire "$1"
    ;;
  -h)
    show_help
    ;;
  *)
    zip_dir "$1"
    ;;
esac
